sudo: required

services:
  - docker

before_install: 
  - docker build -t scotteau/complex_client_for_test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true scotteau/complex_client_for_test npm run test


after_success: 
  - docker build -t scotteau/multi-client ./client
  - docker build -t scotteau/multi-server ./server
  - docker build -t scotteau/multi-nginx ./nginx
  - docker build -t scotteau/multi-worker ./worker

  # login in to docker hub
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push scotteau/multi-client 
  - docker push scotteau/multi-server
  - docker push scotteau/multi-nginx 
  - docker push scotteau/multi-worker


  