version: '3'

services:
  client:
    stdin_open: true
    build: 
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/app/node_modules
      - ./client:/opt/app

  worker:
    build: 
      context: ./worker/
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker:/opt/app
      - /opt/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  api:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/app/node_modules
      - ./server:/opt/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  redis: 
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password
  
  nginx: 
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - client
      - api

